//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Gestion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesGestion : DbContext
    {
        public EntitiesGestion()
            : base("name=EntitiesGestion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBLUSUARIO> TBLUSUARIO { get; set; }
        public DbSet<TBLUSUARIOROL> TBLUSUARIOROL { get; set; }
        public DbSet<TBLROL> TBLROL { get; set; }
        public DbSet<TBLMENU> TBLMENU { get; set; }
    }
}
