//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Gestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMENU
    {
        public decimal MENU_ID { get; set; }
        public string MENU_NOMBRE { get; set; }
        public decimal MENU_GRUPO { get; set; }
        public decimal MENU_FUNCMAIN { get; set; }
        public Nullable<decimal> MENU_FUNCSEC { get; set; }
        public string MENU_URL { get; set; }
    }
}
